name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH client
      run: sudo apt-get install openssh-client

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: 89.116.192.253
        username: u725173075
        key: 65002
        port: ${{ secrets.HOSTINGER_PORT }}
        script: |
          cd public_html/github-actions
          git pull origin main
